# Generated by Django 5.2.3 on 2025-06-27 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='assets/')),
                ('type', models.CharField(choices=[('model', 'Modelo'), ('image', 'Imagen'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('size_mb', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='targets/')),
                ('fset', models.FileField(blank=True, upload_to='targets/')),
                ('fset3', models.FileField(blank=True, upload_to='targets/')),
                ('iset', models.FileField(blank=True, upload_to='targets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.experience')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transform', models.JSONField(default=dict)),
                ('autoplay', models.BooleanField(default=False)),
                ('loop', models.BooleanField(default=False)),
                ('face_user', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asset')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.experience')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.target')),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='targets',
            field=models.ManyToManyField(blank=True, to='core.target'),
        ),
    ]
