# Generated by Django 5.2.3 on 2025-07-06 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_target_mindfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='mindfile',
            new_name='pattfile',
        ),
        migrations.RemoveField(
            model_name='target',
            name='fset',
        ),
        migrations.RemoveField(
            model_name='target',
            name='fset3',
        ),
        migrations.RemoveField(
            model_name='target',
            name='iset',
        ),
    ]
