# Generated by Django 5.2.3 on 2025-07-06 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_mindfile_target_pattfile_remove_target_fset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceasset',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ea_set', to='core.target'),
        ),
    ]
